# Generated by Django 6.0.3 on 2026-04-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_report_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
